### ISSUE TITLE
Persistent cookies

### ISSUE THREAD

**Issue by ghost** [potyl/Webkit#2]
Hi!

Can you help me with persistent cookies?
How can I enable persistent cookies using Gtk3::WebKit ?

Thank you!

**Comment by potyl** [comment]
A quick websearch shows that you might be able via the module HTTP::Soup. See this [python stackoverlow question](http://stackoverflow.com/questions/7766445/python-webkit-webview-remember-cookies). At the end this is just a question of telling the proper C libraries on how to play together.

**Comment by ghost** [comment]
Looks like this code works for me:

my $cookiejar = HTTP::Soup::CookieJarText->new('/tmp/cookies.txt', 0);
$cookiejar->set_accept_policy('SOUP_COOKIE_JAR_ACCEPT_ALWAYS');

my $session = Gtk3::WebKit::get_default_session();
$session->add_feature($cookiejar);

**Comment by potyl** [comment]
Excellent!

**Comment by potyl** [comment]
Can I close the issue?

**Comment by ghost** [comment]
Yes! Thank you!
